Name = "Fast_Cutscenes"
Description = "Death's Door Plugin to speed up or skip a lot of cutscenes"
Dependencies = []
Integrations = []
Link = "https://github.com/SpR3AD1/Fast_cutscenes/releases/download/1.0.7/Fast_cutscenes.zip"
SHA256 = "db9f2d4c5aaa84f49a5b9bb5acc4f22fc73f8168ebc774c3f274b72777adb92b"
Repository = "https://github.com/SpR3AD1/Fast_cutscenes"
