Name = "ItemChanger"
Description = "Replaces item pickups with other items"
Dependencies = []
Integrations = ["RecentItemsDisplay"]
Link = "https://github.com/dpinela/DeathsDoor.ItemChanger/releases/download/v1.5/ItemChanger.zip"
SHA256 = "ae419742fa0c612e9e3da463d7c38ef50d91fc92c3830dcd81c35fce38f26583"
Repository = "https://github.com/dpinela/DeathsDoor.ItemChanger/"
