Name = "ItemChanger"
Description = "Replaces item pickups with other items"
Dependencies = []
Integrations = ["RecentItemsDisplay"]
Link = "https://github.com/dpinela/DeathsDoor.ItemChanger/releases/download/v1.4/ItemChanger.zip"
SHA256 = "5d2ea866bcc938def1bdf5d60da7d7be8a284a9092573a2dd5f0338e3c989348"
Repository = "https://github.com/dpinela/DeathsDoor.ItemChanger/"
