Name = "ItemChanger"
Description = "Replaces item pickups with other items"
Dependencies = []
Integrations = ["RecentItemsDisplay"]
Link = "https://github.com/dpinela/DeathsDoor.ItemChanger/releases/download/v1.2/ItemChanger.zip"
SHA256 = "d3811b23c37a462333e6dd84a5f4f5259edc4286323ac6d0de96afff659ada02"
Repository = "https://github.com/dpinela/DeathsDoor.ItemChanger/"
