Name = "ItemChanger"
Description = "Replaces item pickups with other items"
Dependencies = []
Integrations = ["RecentItemsDisplay"]
Link = "https://github.com/dpinela/DeathsDoor.ItemChanger/releases/download/v1.3/ItemChanger.zip"
SHA256 = "eba4e7b85b8b5f972677e1f28138ce08e85346146d05d16985fbc204acd3f4a9"
Repository = "https://github.com/dpinela/DeathsDoor.ItemChanger/"
