Name = "Plando"
Description = "Allows you to play planned randomizers, AKA plandos"
Dependencies = ["AlternativeGameModes", "ItemChanger"]
Integrations = []
Link = "https://github.com/dpinela/DeathsDoor.Plando/releases/download/v1.1/Plando.zip"
SHA256 = "71e9f3719f29efff40ddf14a8b6741bc48a1f43d83ee780ad67e713221f39729"
Repository = "https://github.com/dpinela/DeathsDoor.Plando/"
