Name = "Randomizer"
Description = "Item randomizer game mode"
Dependencies = ["AlternativeGameModes", "ItemChanger", "RandomizerCore", "RandomizerCore.Json"]
Integrations = []
Link = "https://github.com/dpinela/DeathsDoor.Randomizer/releases/download/v1.2/Randomizer.zip"
SHA256 = "5ebfec0dad49e12bac9976d14f4fcfe648815f894164d688a75e472b4249082a"
Repository = "https://github.com/dpinela/DeathsDoor.Randomizer/"
