Name = "RandomizerCore.Json"
Description = "A library to serialize RC data structures"
# ItemChanger is where the Newtonsoft.Json dll is currently
# bundled. This should change at some point.
Dependencies = ["RandomizerCore", "ItemChanger"]
Integrations = []
Link = "https://github.com/homothetyhk/RandomizerCore.Json/releases/download/v1.0.1/RandomizerCore.Json.zip"
SHA256 = "3821dc60fa1c8d53e4af3d2cb86b1615f169e5112b8656e7a1f9fcc5a0c7a1e5"
Repository = "https://github.com/homothetyhk/RandomizerCore.Json"