Name = "Randomizer"
Description = "Item randomizer game mode"
Dependencies = ["AlternativeGameModes", "ItemChanger", "RandomizerCore"]
Integrations = []
Link = "https://github.com/dpinela/DeathsDoor.Randomizer/releases/download/v1.1/Randomizer.zip"
SHA256 = "18e08c80231a4309fd80e4abd49be36af204f44d9b1769484b629b988689473f"
Repository = "https://github.com/dpinela/DeathsDoor.Randomizer/"
