Name = "Randomizer"
Description = "Item randomizer game mode"
Dependencies = ["AlternativeGameModes", "ItemChanger", "RandomizerCore", "RandomizerCore.Json"]
Integrations = []
Link = "https://github.com/dpinela/DeathsDoor.Randomizer/releases/download/v1.3/Randomizer.zip"
SHA256 = "e50d230b9b9d9c981ba128a773bbb4a061943b5349bbec0025e35c60198109bb"
Repository = "https://github.com/dpinela/DeathsDoor.Randomizer/"
