Name = "Randomizer"
Description = "Item randomizer game mode"
Dependencies = ["AlternativeGameModes", "ItemChanger", "RandomizerCore", "RandomizerCore.Json"]
Integrations = []
Link = "https://github.com/dpinela/DeathsDoor.Randomizer/releases/download/v1.2.1/Randomizer.zip"
SHA256 = "2686e5a28eca8119c8c33e3a170a1909d2659a06bcf84f4f05a39c903c799155"
Repository = "https://github.com/dpinela/DeathsDoor.Randomizer/"
