Name = "Randomizer"
Description = "Item randomizer game mode"
Dependencies = ["AlternativeGameModes", "ItemChanger", "RandomizerCore", "RandomizerCore.Json"]
Integrations = []
Link = "https://github.com/dpinela/DeathsDoor.Randomizer/releases/download/v1.3.1/Randomizer.zip"
SHA256 = "0fefec2cc52b7993e4aa06ae6d6644c595f62d10576db803fde321ab5cec4451"
Repository = "https://github.com/dpinela/DeathsDoor.Randomizer/"
