Name = "RecentItemsDisplay"
Description = "Displays items recently acquired through ItemChanger"
Dependencies = ["ItemChanger", "MagicUI"]
Integrations = []
Link = "https://github.com/dpinela/DeathsDoor.RecentItemsDisplay/releases/download/v1.1/RecentItemsDisplay.zip"
SHA256 = "adc1365a48dd2f076568c21eef99653252bcdca2a99f0c120fa1e9ebddb8ded3"
Repository = "https://github.com/dpinela/DeathsDoor.RecentItemsDisplay"