Name = "RecentItemsDisplay"
Description = "Displays items recently acquired through ItemChanger"
Dependencies = ["ItemChanger", "MagicUI"]
Integrations = ["ConfigurationManager"]
Link = "https://github.com/dpinela/DeathsDoor.RecentItemsDisplay/releases/download/v1.2/RecentItemsDisplay.zip"
SHA256 = "8ef58a3510aa1c36ff2de0a67557397e78306c81aa0b30c82f4d8f652dda411e"
Repository = "https://github.com/dpinela/DeathsDoor.RecentItemsDisplay"